### PR TITLE
Fixed "Issue" #1

### LINKED ISSUE #2: Add basic list view
# Description
Show a very basic list. The list will only allow users to add new items. They can not edit or remove items. They can only have one list for now. Those features will be added in the future.

# Proposal
* Copy `MyHomePage` and `_MyHomePageState` to a new file, called `list-widget.dart`.
* Rename `MyHomePage` to `ListWidget`
    * _Hint - click on the `MyHomePage` name in your code and use the F2 keyboard shortcut to quickly rename the widget!_
* Rework `ListWidget` to use a `ListView` instead of `Center`
* When the user taps the "plus" button, a new item should be added to the list
* Each new item should contain the text "New Item".

### PR DESCRIPTION
**Pull request by tycebrown**
1. Refactored the HomePage into a ListWidget.
2. Set body to a list view.

### CODE REVIEW

**Comment by tycebrown** [comment]
Note that it has not been styled.

**Comment by Pertempto** [comment]
Just quickly skimming over the code, it looks pretty good! When I get the chance to sit down at my computer and take a deeper look I'll do a full review. That might be this weekend or early next week.

File: lib/list_widget.dart [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    );
+  }
+
+  void _addNewItem() {
+    final itemToAdd = ListTile(
+      title: Text(
+        'New item',
+        style: itemTextStyle,
+      ),
+    );
```
Comment (Pertempto) [inline lib/list_widget.dart]:
```suggestion
    const itemTextStyle = Theme.of(context).textTheme.titleLarge
    final itemToAdd = ListTile(
      title: Text(
        'New item',
        style: itemTextStyle,
      ),
    );
```
Instead of making your own text style, I would recommend using one of the built-in ones from [here](https://api.flutter.dev/flutter/material/TextTheme-class.html). Using the built-in ones will lead to more consistency in your apps.

File: lib/list_widget.dart [hunk 2]
```diff
@@ -0,0 +1,51 @@
+import 'package:flutter/material.dart';
+
+class ListWidget extends StatefulWidget {
```
Comment (Pertempto) [inline lib/list_widget.dart:6]: Include some kind of header comment above the widget that explains its purpose.

File: lib/list_widget.dart [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+  const ListWidget({super.key});
+
+  @override
+  State<ListWidget> createState() => _ListWidgetState();
+}
+
+class _ListWidgetState extends State<ListWidget> {
+  static const itemTextStyle = TextStyle(fontSize: 20);
+
+  final list = <Widget>[];
```
Comment (Pertempto) [inline lib/list_widget.dart]: This is the data part of your app. It is strange to store it as a list of Widgets. What if the user wants to edit one of the items? We need to write our code in such a way that we can easily add more features in the future. Instead, I would recommend storing it as a list of strings.

File: lib/list_widget.dart [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+  }
+
+  ListView _buildListView() {
+    // note:
+    // I set children equal to a copy of list instead of just
+    // list because ListView expects that its children parameter will
+    // not be modified once it is passed in.
+    //
+    return ListView(
+      children: list.toList(),
```
Comment (Pertempto) [inline lib/list_widget.dart]: If `list` was a list of strings, you could do something like `children: list.map((item) => _buildItemView(item))`

File: lib/list_widget.dart [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+    );
+  }
+
+  void _addNewItem() {
```
Comment (Pertempto) [inline lib/list_widget.dart:39]: In this method, instead of adding widgets to `list`, add a string. You can convert the strings to widgets at render-time in `_buildListView`.

File: lib/list_widget.dart (hunk 3 above)
Comment (Pertempto) [reply lib/list_widget.dart]: Using descriptive variables names is a very important part of coding. `list` is about as vague as you can get. `List` is a built-in class in Dart, so you don't want a variable called `list`. A future reader of the code could easily be confused by this name. What if you named it something like `listItems`?

**Comment by Pertempto** [comment]
@tycebrown I have completed my first review of this pull request. The functionality works great, the code just needs some cleanup.  
* Please address each of the items I mentioned above.
    * Respond with "done" or something similar to each item when they have been completed
         * Please do *not* click the "Resolve conversation" button
         * I will click it after I have confirmed that you have applied the necessary fix
* When you have addressed all the items, please remove the "changes requested" label, and leave a comment asking me to look over this again.

File: lib/list_widget.dart (hunk 1 above)
Comment (tycebrown) [reply lib/list_widget.dart]: Done!

File: lib/list_widget.dart (hunk 2 above)
Comment (tycebrown) [reply lib/list_widget.dart:6]: Done!

File: lib/list_widget.dart (hunk 3 above)
Comment (tycebrown) [reply lib/list_widget.dart]: Done!

File: lib/list_widget.dart (hunk 4 above)
Comment (tycebrown) [reply lib/list_widget.dart]: Done!

File: lib/list_widget.dart (hunk 5 above)
Comment (tycebrown) [reply lib/list_widget.dart:39]: Done!

**Comment by tycebrown** [comment]
Done and ready!

File: lib/list_widget.dart [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+
+  Widget _buildItemWidget(String item) {
+    final itemTextStyle = Theme.of(context).textTheme.titleLarge;
+    return ListTile(
+      title: Text(
+        item,
+        style: itemTextStyle,
+      ),
+    );
+  }
```
Comment (Pertempto) [inline lib/list_widget.dart]: My personal preference is to keep my code in as least amount of lines as a I can (within reason).   
For these two methods, I would remove the trailing commas and write them as follows:  
```suggestion
  ListView _buildListView() => ListView(
      children: listItems.map((item) => _buildItemWidget(item)).toList());

  Widget _buildItemWidget(String item) {
    final itemTextStyle = Theme.of(context).textTheme.titleLarge;
    return ListTile(title: Text(item, style: itemTextStyle));
  }
```
That's 7 lines of code, instead of 19. This makes it easier to see more code on one screen, without having to scroll. This is just a style preference. If you find it easier to read as it is, then don't change anything and just leave a comment.

File: lib/list_widget.dart [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+
+  void _addNewItem() {
+    final itemToAdd = 'New Item';
+
+    setState(() => listItems.add(itemToAdd));
+  }
+}
```
Comment (Pertempto) [inline lib/list_widget.dart]:
```suggestion
  void _addNewItem() {
    final itemToAdd = 'New Item';
    setState(() => listItems.add(itemToAdd));
  }
}
```  
The extra blank line isn't really adding anything.

File: lib/list_widget.dart [hunk 8]
```diff
@@ -0,0 +1,57 @@
+import 'package:flutter/material.dart';
+
+///ListWidget: 
+///  - a widget representing a page containing a single list in the 
+///  app, such as a to-do list, a shopping list, etc.
+
+class ListWidget extends StatefulWidget {
```
Comment (Pertempto) [inline lib/list_widget.dart]:
```suggestion
/// ListWidget: 
///  - a widget representing a page containing a single list in the 
///  app, such as a to-do list, a shopping list, etc.
class ListWidget extends StatefulWidget {
```
Don't leave blank line after the comment, be sure to leave a space between the `///` and your words.

**Comment by Pertempto** [comment]
Three style-related things to address, and then we'll be done here!

**Comment by tycebrown** [comment]
Committed & pushed your style changes.

**Review by Pertempto — APPROVED** [review]
Everything looks great!  
Good work!!
