### PR TITLE
Made checklist creation easier, and fixed a small bug

### LINKED ISSUE #25: Make Checklist Creation Easier
If you want to add a bunch of checkbox items, you add the items, and the you have to go back to enable the checkbox type.  

What if each new item in the list took their `itemType` value from the last item in the list? Then the user just has to add the first checkbox item, and all the rest would automatically match it.

### PR DESCRIPTION
**Pull request by tycebrown**
When an item is edited after searching, sometimes, it would not update in the app after the user went out of the list and coming back (though it would in the database). 

I made the default item type for a new item the item type of the last item in `items`.

Closes #25

### CODE REVIEW

**Comment by Pertempto** [comment]
You don't need to include `(see description)` in the title. People should always read the description. Also please include the issue number in your description in the format: `Closes #25`

**Comment by Pertempto** [comment]
This is a more descriptive PR title 👍🏽 There is no need to include issue numbers in your PR titles. Include the issue number in the description with "closes". That way GitHub will automatically link the PR with the issue.

File: lib/model/list_model.dart [hunk 1]
```diff
@@ -14,13 +15,16 @@ class ListModel {
 
   final items = IsarLinks<Item>();
 
+  ItemType getDefaultItemType() => items.lastOrNull?.itemType ?? ItemType.text;
```
Comment (Pertempto) [inline lib/model/list_model.dart]:
```suggestion
  ItemType get lastItemType => items.lastOrNull?.itemType ?? ItemType.text;
```
This is where it would be cleaner to use a [getter](https://dart.dev/language/methods#getters-and-setters). We can also make the name more accurate.

File: lib/view/list_widget.dart [hunk 2]
```diff
@@ -72,7 +73,7 @@ class _ListWidgetState extends State<ListWidget> {
           .toList());
 
   void _addNewItem() async {
-    final newItem = Item();
+    final newItem = Item('', listModel.getDefaultItemType());
```
Comment (Pertempto) [inline lib/view/list_widget.dart]:
```suggestion
    // Imitate the type of the last item.
    final newItem = Item('', listModel.lastItemType);
```

**Review by Pertempto — CHANGES_REQUESTED** [review]

File: lib/model/list_model.dart [hunk 3]
```diff
@@ -49,6 +54,9 @@ class ListModel {
   Future<void> update(Item item) async {
     if (items.contains(item)) {
       await DatabaseManager.putItem(item);
+      // The following ensures that the copy of `item` that `this` has is up to date.
+      items.remove(item);
+      items.add(item);
```
Comment (Pertempto) [inline lib/model/list_model.dart]: This introduces a new bug: when a user updates an item, that item gets moved to the end of the list. You can see the problem occur in the UI by updating a few items, and then adding a new item. Suddenly a bunch of blank spots show up in the UI.  

To maintain order, try something like this (might need modifications):
```suggestion
      // The following ensures that the copy of `item` that `this` has is up to date.
      const index = items.indexOf(item);
      items[index] = item;
```

**Review by Pertempto — CHANGES_REQUESTED** [review]

File: lib/model/list_model.dart (hunk 3 above)
Comment (tycebrown) [reply lib/model/list_model.dart]: Okay, I think I found a fix. What I ended up doing was calling `items.lookup(item)` to get the `Item` object stored in the links and then copying all the fields of `item` (except `id`) onto that object.

File: lib/model/item.dart [hunk 4]
```diff
@@ -15,6 +15,12 @@ class Item {
   bool isChecked = false;
 
   Item([this.value = '', this.itemType = ItemType.text]);
+
+  void copyOnto(Item item) {
```
Comment (Pertempto) [inline lib/model/item.dart:22]: It would be good to include an explanation comment above the method. Explain **why** it is needed, not **what** it does.

**Review by Pertempto — APPROVED** [review]
You shouldn't add the "how is it?" in your commit message.
